### ISSUE TITLE
Few issues

### ISSUE THREAD

**Issue by alenkostic** [vashin1/LineageUI#2]
I really like this UI, but how do i:

- Remove poisons from my weapons as a rogue, since i cant rightclick the poisons to remove them?

- Sometimes if i write alot in the chat, i cant see my own text and have to either wait some time or do a /reload. 

- Is it possible to completely disable the Shapeshift bar, i can only autohide it?

- I have figured out how to move the WIM minimap icon but how do i remove the border around the icon, like you have done?

**Comment by vashin1** [comment]
1)  You cannot remove poisons or weapon buffs in Vanilla WoW (Try it for yourself with no addons enabled)
2) Sounds like the server muted you, try not to send to much chat in public/global channels in a short period of time
3) The newest release of pfUI that I include allows you to drag frames off screen if you enable the option in the settings menu, perhaps this would suit your needs
4) That is a custom change by me, https://drive.google.com/open?id=0B5QT3H5F-mBXRUJlbG1tMmNPTzA

use that version of WIM :)

**Comment by alenkostic** [comment]
Thank you :)
